name: Presubmit
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-format-18
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check format
        shell: bash
        run: |
          set +e
          git-clang-format --binary clang-format-18 --diff origin/main --extensions cpp,hpp > output.txt
          cat output.txt
          grep -E "(no modified files to format|clang-format did not modify any files)" output.txt
  build-android:
    name: Android Build
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: ccache
          max-size: 2G
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libvulkan-dev
      - name: Clone dependencies
        run: |
          git clone --depth 1 --branch v51.2 https://github.com/google/perfetto third_party/perfetto
          git clone --depth 1 --branch main https://github.com/KhronosGroup/SPIRV-Tools.git third_party/spirv-tools
          git clone --depth 1 --branch main https://github.com/KhronosGroup/SPIRV-Headers.git third_party/spirv-tools/external/spirv-headers
      - name: Download and extract Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip -O android-ndk.zip
          unzip android-ndk.zip -d .
          rm android-ndk.zip
          ls -l
      - name: Build SPIRV-Tools
        shell: bash
        run: |
          cmake -B third_party/spirv-tools/build -S third_party/spirv-tools/ -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_TOOLCHAIN_FILE="$(realpath android-ndk-r27d/build/cmake/android.toolchain.cmake)" \
            -DANDROID_ABI="arm64-v8a" \
            -DANDROID_PLATFORM="35" \
            -DSPIRV_SKIP_TESTS=1 \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build third_party/spirv-tools/build
          cmake --install third_party/spirv-tools/build --prefix $(pwd)/install/
      - name: Build
        shell: bash
        run: |
          cmake -B build -S . -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_TOOLCHAIN_FILE="android-ndk-r27d/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="arm64-v8a" \
            -DANDROID_PLATFORM="35" \
            -DPERFETTO_SDK_PATH="$(pwd)/third_party/perfetto/sdk" \
            -DSPIRV_HEADERS_INCLUDE_PATH="$(pwd)/third_party/spirv-tools/external/spirv-headers/include" \
            -DSPIRV_TOOLS_BUILD_PATH="$(pwd)/third_party/spirv-tools/build" \
            -DSPIRV_TOOLS_SOURCE_PATH="$(pwd)/third_party/spirv-tools" \
            -DSPIRV-Tools_DIR="$(pwd)/install/lib/cmake/SPIRV-Tools" \
            -DSPIRV-Tools-opt_DIR="$(pwd)/install/lib/cmake/SPIRV-Tools-opt" \
            -DVKSP_SKIP_EXTRACTOR=1 \
            -DVKSP_SKIP_MERGE_BUFFERS=1 \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build
  build:
    name: Builds & Tests
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: ccache
          max-size: 2G
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libvulkan-dev clang-17 mesa-vulkan-drivers
      - name: Build SPIRV-Tools
        run: |
          git clone --depth 1 --branch main https://github.com/KhronosGroup/SPIRV-Tools.git third_party/spirv-tools
          git clone --depth 1 --branch main https://github.com/KhronosGroup/SPIRV-Headers.git third_party/spirv-tools/external/spirv-headers
          cmake -B third_party/spirv-tools/build -S third_party/spirv-tools/ -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER="$(which clang++)" \
            -DSPIRV_SKIP_TESTS=1 \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build third_party/spirv-tools/build
          cmake --install third_party/spirv-tools/build --prefix $(pwd)/install/
      - name: Build Perfetto
        run: |
          git clone --depth 1 --branch v51.2 https://github.com/google/perfetto third_party/perfetto
          $(pwd)/third_party/perfetto/tools/install-build-deps
          $(pwd)/third_party/perfetto/tools/setup_all_configs.py --ccache
          $(pwd)/third_party/perfetto/tools/ninja -C $(pwd)/third_party/perfetto/out/linux_clang_release libtrace_processor.a perfetto traced
      - name: Install Vulkan-Loader dependencies
        run: |
          sudo apt-get install build-essential libx11-xcb-dev libxkbcommon-dev libwayland-dev libxrandr-dev
      - name: Build Vulkan-Loader
        run : |
          git clone --depth 1 --branch v1.3.280 https://github.com/KhronosGroup/Vulkan-Loader.git third_party/vulkan-loader
          cmake -B third_party/vulkan-loader/build -S third_party/vulkan-loader -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DVulkanHeaders_DIR=$(pwd)/install/share/cmake/VulkanHeaders \
            -DCMAKE_CXX_COMPILER="$(which clang++)" \
            -DCMAKE_C_COMPILER="$(which clang)" \
            -DUPDATE_DEPS=ON \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build third_party/vulkan-loader/build
      - name: Build debug
        run: |
          cmake -B build_debug -S . -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DPERFETTO_SDK_PATH="$(pwd)/third_party/perfetto/sdk" \
            -DPERFETTO_INTERNAL_INCLUDE_PATH="$(pwd)/third_party/perfetto/include" \
            -DPERFETTO_GEN_INCLUDE_PATH="$(pwd)/third_party/perfetto/out/linux_clang_release/gen/build_config" \
            -DPERFETTO_TRACE_PROCESSOR_LIB="$(pwd)/third_party/perfetto/out/linux_clang_release/libtrace_processor.a" \
            -DPERFETTO_CXX_CONFIG_INCLUDE_PATH="$(pwd)/third_party/perfetto/buildtools/libcxx_config" \
            -DPERFETTO_CXX_SYSTEM_INCLUDE_PATH="$(pwd)/third_party/perfetto/buildtools/libcxx/include" \
            -DSPIRV_HEADERS_INCLUDE_PATH="$(pwd)/third_party/spirv-tools/external/spirv-headers/include" \
            -DSPIRV_TOOLS_BUILD_PATH="$(pwd)/third_party/spirv-tools/build" \
            -DSPIRV_TOOLS_SOURCE_PATH="$(pwd)/third_party/spirv-tools" \
            -DEXTRACTOR_NOSTDINCXX=1 \
            -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH};$(pwd)/install/lib/cmake/SPIRV-Tools-opt;$(pwd)/install/lib/cmake/SPIRV-Tools" \
            -DCMAKE_CXX_COMPILER="$(which clang++)" \
            -DCMAKE_BUILD_TYPE=Debug
          cmake --build build_debug
      - name: Build release
        run: |
          cmake -B build_release -S . -G Ninja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DPERFETTO_SDK_PATH="$(pwd)/third_party/perfetto/sdk" \
            -DPERFETTO_INTERNAL_INCLUDE_PATH="$(pwd)/third_party/perfetto/include" \
            -DPERFETTO_GEN_INCLUDE_PATH="$(pwd)/third_party/perfetto/out/linux_clang_release/gen/build_config" \
            -DPERFETTO_TRACE_PROCESSOR_LIB="$(pwd)/third_party/perfetto/out/linux_clang_release/libtrace_processor.a" \
            -DPERFETTO_CXX_CONFIG_INCLUDE_PATH="$(pwd)/third_party/perfetto/buildtools/libcxx_config" \
            -DPERFETTO_CXX_SYSTEM_INCLUDE_PATH="$(pwd)/third_party/perfetto/buildtools/libcxx/include" \
            -DSPIRV_HEADERS_INCLUDE_PATH="$(pwd)/third_party/spirv-tools/external/spirv-headers/include" \
            -DSPIRV_TOOLS_BUILD_PATH="$(pwd)/third_party/spirv-tools/build" \
            -DSPIRV_TOOLS_SOURCE_PATH="$(pwd)/third_party/spirv-tools" \
            -DEXTRACTOR_NOSTDINCXX=1 \
            -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH};$(pwd)/install/lib/cmake/SPIRV-Tools-opt;$(pwd)/install/lib/cmake/SPIRV-Tools" \
            -DCMAKE_CXX_COMPILER="$(which clang++)" \
            -DBACKEND=System \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build_release
      - name: Test runner
        env:
          VKSP_RUNNER: ${{ github.workspace }}/build_release/runner/vulkan-shader-profiler-runner
        run: |
          $(pwd)/tests/test-runner.sh
      - name: Test layer & extractor
        env:
          VK_LOADER_DEBUG: all
          LD_LIBRARY_PATH: ${{ github.workspace }}/build_release/layer/:${{ github.workspace }}/third_party/vulkan-loader/build/loader/:$LD_LIBRARY_PATH
          VKSP_EXTRACTOR: ${{ github.workspace }}/build_release/extractor/vulkan-shader-profiler-extractor
          VKSP_RUNNER: ${{ github.workspace }}/build_release/runner/vulkan-shader-profiler-runner
          PERFETTO_TRACED: ${{ github.workspace }}/third_party/perfetto/out/linux_clang_release/traced
          PERFETTO_BINARY: ${{ github.workspace }}/third_party/perfetto/out/linux_clang_release/perfetto
        run: |
          $(pwd)/tests/test-extractor.sh
      - name: Test buffers
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/build_release/layer/:${{ github.workspace }}/third_party/vulkan-loader/build/loader/:$LD_LIBRARY_PATH
          VKSP_RUNNER: ${{ github.workspace }}/build_release/runner/vulkan-shader-profiler-runner
          VKSP_MERGE_BUFFERS: ${{ github.workspace}}/build_release/merge-buffers/vulkan-shader-profiler-merge-buffers
          PERFETTO_TRACED: ${{ github.workspace }}/third_party/perfetto/out/linux_clang_release/traced
          PERFETTO_BINARY: ${{ github.workspace }}/third_party/perfetto/out/linux_clang_release/perfetto
        run: |
          $(pwd)/tests/test-buffers.sh

